### PR TITLE
Make devshell optional, remove unused inputs

### PR DESCRIPTION
**Pull request by SuperSandro2000**
In the vein off https://github.com/nix-community/lanzaboote/pull/282 and https://github.com/nix-community/nixvim/pull/1829

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I first only tested this with a config where tsnsrv was not actually used and quickly noticed that a lib.optionalAttrs is required 😅 

Also very bad timing with that force push 🙈

**Comment by antifuchs** [comment]
Hahaha, no worries - I noticed in time that you were still working on it. LMK when you're finished trying it out and I'll merge

**Comment by antifuchs** [comment]
Ah, oof - this needs a run of `nix fmt`, if you could!

**Comment by SuperSandro2000** [comment]
done

**Comment by antifuchs** [comment]
thanks again! (:

**Pull request merged**
